name: debug_run
ckpt_path: null

# Save Directories
run_dir: exp/runs/${name}
hydra:
  run:
    dir: ${run_dir}

# Imports
defaults:
  - data: gtzan_5s
  - model: 5s
  - _self_

# Custom Params
batch_size: 1024
num_workers: 32
float32_matmul_precision: medium
compile: True
seed: 3

# Trainer Params
trainer:
  _target_: lightning.pytorch.Trainer
  default_root_dir: ${run_dir}
  max_steps: 350000
  devices: 1
  accelerator: gpu
  strategy: ddp
  precision: 32
  enable_checkpointing: True
  log_every_n_steps: 3
  

# Optimizers/Schedulers
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

# Logger
logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: genre_classification
  name: ${name}
  save_dir: ${run_dir}
  id: null
